### ISSUE TITLE
DOUBLE TIGT

### ISSUE THREAD

**Issue by brendonavalos** [brittonwalker/savage_wordpress#17]
<img width="1405" alt="screen shot 2017-12-09 at 10 23 40 am" src="https://user-images.githubusercontent.com/15132554/33796866-0acbbed4-dccb-11e7-8e1a-bf0849d9568f.png">

The title shouldnt be repeated in the center text column. thats just for painting info.

**Comment by brittonwalker** [comment]
This has to do with the way Andrew put content in for the image caption and not code.
